/*----- PROTECTED REGION ID(HdbppHealthCheckStateMachine.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        HdbppHealthCheckStateMachine.cpp
//
// description : State machine file for the HdbppHealthCheck class
//
// project :     HdbppHealthCheck
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
// Copyright (C): 2019
//                European Synchrotron Radiation Facility
//                BP 220, Grenoble 38043
//                France
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <HdbppHealthCheck.h>

/*----- PROTECTED REGION END -----*/	//	HdbppHealthCheck::HdbppHealthCheckStateMachine.cpp

//================================================================
//  States   |  Description
//================================================================
//  ALARM    |  
//  FAULT    |  
//  ON       |  
//  UNKNOWN  |  


namespace HdbppHealthCheck_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================


//=================================================
//		Commands Allowed Methods
//=================================================


/*----- PROTECTED REGION ID(HdbppHealthCheck::HdbppHealthCheckStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	HdbppHealthCheck::HdbppHealthCheckStateAllowed.AdditionalMethods

}	//	End of namespace
